from interpreter import *
keywords = {
    "and": AND,
    "else": ELSE,
    "false": FALSE,
    "for": FOR,
    "foreach": FOR_EACH,
    "fn": FUN,
    "cls": CLASS,
    "if": IF,
    "elif": ELSE_IF,
    "nil": NULL,
    "print": PRINT,
    "println": PRINTLN,
    "return": RETURN,
    "break": BREAK,
    "continue": CONTINUE,
    "in": IN,
    "true": TRUE,
    "int": TYPE_INTEGER,
    "str": TYPE_STRING,
    "float": TYPE_FLOAT,
    "bool": TYPE_BOOLEN,
    "array": TYPE_ARRAY,
    "while": WHILE,
    "raise": RAISE,
    "http": HTTP,
    "ftp": FTP,
    "stmp": STMP,
    "tcp": TCP,
    "ip": IP,
    "ssl": SSL,
}
